# Generated by Django 2.2.3 on 2019-07-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('brand_new', models.BooleanField(default=False)),
                ('recommended', models.BooleanField(default=True)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
