# Generated by Django 2.2.3 on 2019-07-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
