# Generated by Django 2.2.3 on 2019-07-23 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190722_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=256)),
                ('offer_price', models.FloatField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.Games')),
            ],
        ),
    ]
