# Generated by Django 2.2.3 on 2019-08-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_offers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offers',
        ),
    ]
